"""
Tests for 5 Deterministic Tools, Sandbox, Verifier, and Audit Trail
"""
import pytest
from backend.core.tools import (
    list_files,
    read_file,
    search_documents,
    create_file,
    create_folder,
    execute_tool,
    _safe_resolve_path
)
from backend.core.verifier import action_verifier
from backend.core.audit import audit_logger

def test_tool_list_files():
    res = list_files("")
    assert res["total_items"] > 0
    names = [i["name"] for i in res["items"]]
    assert "Alex_Rivera_Resume.md" in names

def test_tool_read_file():
    res = read_file("Alex_Rivera_Resume.md")
    assert "Alex Rivera" in res["content"]
    assert res["size_bytes"] > 0

def test_tool_sandbox_prevents_traversal():
    with pytest.raises(PermissionError):
        _safe_resolve_path("../../windows/system32/cmd.exe")

    with pytest.raises(PermissionError):
        _safe_resolve_path("../backend/app.py")

def test_create_file_and_verify():
    test_filepath = "test_output/sample_output.md"
    test_content = "# Verified Test Document\n\nThis is a test output document generated by LocalGPT."
    
    # Execute tool
    res = execute_tool("create_file", {"filepath": test_filepath, "content": test_content})
    assert res.success is True
    assert res.risk_level == "HIGH"

    # Verify action
    verification = action_verifier.verify_action("create_file", {"filepath": test_filepath, "content": test_content})
    assert verification.verified is True
    assert any(c.name == "file_exists" and c.passed for c in verification.checks)
    assert any(c.name == "non_empty_size" and c.passed for c in verification.checks)

def test_audit_logging():
    entry = audit_logger.log_event(
        event_type="TEST_EVENT",
        session_id="test_sess_1",
        action="read_file",
        details={"status": "ok"}
    )
    assert entry["event_type"] == "TEST_EVENT"
    assert entry["session_id"] == "test_sess_1"

    entries = audit_logger.get_entries(session_id="test_sess_1")
    assert len(entries) >= 1
